version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_DATABASE}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432" # Expose for local development and debugging

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379" # Expose for local development and debugging

  web:
    build:
      context: .
      dockerfile: server/web/Dockerfile
    restart: unless-stopped
    command: uvicorn server.web.app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  server_bot:
    build:
      context: .
      dockerfile: server/server_bot/Dockerfile
    restart: unless-stopped
    command: python server/server_bot/bot.py
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
