"""add_video_permissions_table

Revision ID: 009_add_video_permissions_table
Revises: 008_add_channel_and_playlist_models
Create Date: 2024-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '009_add_video_permissions_table'
down_revision = '008_add_channel_and_playlist_models'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_permissions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('video_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('permission_type', sa.String(length=50), nullable=False),
    sa.Column('granted_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'user_id', 'permission_type', name='uq_video_user_permission')
    )
    op.create_index(op.f('ix_video_permissions_user_id'), 'video_permissions', ['user_id'], unique=False)
    op.create_index(op.f('ix_video_permissions_video_id'), 'video_permissions', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_permissions_video_id'), table_name='video_permissions')
    op.drop_index(op.f('ix_video_permissions_user_id'), table_name='video_permissions')
    op.drop_table('video_permissions')
    # ### end Alembic commands ###